import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title:"Terms and Conditions | Nina Kurain", description:"India-first terms for subscriptions, creator content, AI tools, and community safety." };

export default function TermsAndConditionsPage(){
  return <div className="legal-shell"><header className="legal-header"><div className="legal-header-inner"><div className="legal-brand"><Link href="/" className="legal-brand-link"><span className="legal-brand-dot"/><span className="legal-brand-title">NINA KURAIN</span></Link><span className="legal-badge">TERMS &amp; SAFETY</span></div><div className="legal-nav-actions"><Link href="/" className="legal-btn legal-btn-secondary">Back to Home</Link><Link href="/privacy-policy" className="legal-btn legal-btn-secondary">Privacy Policy</Link><Link href="/content-removal" className="legal-btn legal-btn-secondary">Report Content</Link></div></div></header><main className="legal-main" style={{maxWidth:920,margin:"0 auto",padding:"48px 24px"}}>
    <h1 className="legal-title">Terms and Conditions</h1><p className="legal-meta">Version 4.0.0 · Last updated 30 September 2026 · India</p>
    <div className="legal-callout highlight"><h2>Important: a community for ordinary, consensual content</h2><p>This service is for lawful everyday hangout photos, videos, creator subscriptions, and clearly labelled AI-assisted creative work. Sexual exploitation, nudity intended to arouse, intimate imagery, non-consensual content, deepfakes, impersonation, and any content involving minors are prohibited.</p></div>
    <section className="legal-section"><h2>1. Who operates the service</h2><p>The service is operated by the legal entity shown in the checkout, invoices, and contact settings. Before accepting payments, the operator must publish its registered legal name, address, support contact, GST details where applicable, and India grievance officer details. Do not launch paid services while those details remain placeholders.</p></section>
    <section className="legal-section"><h2>2. Eligibility and accounts</h2><p>You must be at least 18 years old, provide accurate account information, protect your credentials, and use the service lawfully. We may require email, phone, identity, or additional verification for fraud prevention, creator onboarding, or safety investigations.</p></section>
    <section className="legal-section"><h2>3. Subscriptions and payments</h2><p>Prices are displayed in Indian rupees and include or exclude applicable taxes as stated at checkout. Razorpay processes payments; access is granted only after server-side payment confirmation. A payment may remain pending until Razorpay confirms capture and settlement. Recurring billing, renewal date, cancellation, refund, and tax information are shown before purchase and on the receipt.</p><p>Creator and AI-credit purchases are separate products. A creator application fee of ₹250 per year is non-transferable and is not an approval guarantee. Refunds, chargebacks, failed payments, and statutory consumer rights are handled under applicable Indian law and the disclosed refund policy.</p></section>
    <section className="legal-section"><h2>4. Creator programme and 10% platform fee</h2><p>Members may apply to become creators. Approval requires safety review, identity/KYC and payout checks appropriate to the service, rights/consent attestations, and any legally required tax information. Creator earnings are recorded only after a captured payment and remain pending until the disclosed settlement window and any fraud/refund hold expire. The platform retains 10% of eligible creator subscription revenue as its platform fee; payment gateway charges, taxes, refunds, chargebacks, and withholding may also apply. Payouts are never guaranteed merely because a sale occurred.</p></section>
    <section className="legal-section"><h2>5. Uploads, rights, and AI disclosure</h2><p>You retain ownership of your work, but grant us a limited licence to store, review, transform, and display it only to provide the service. You must own or have permission for every uploaded asset and must have consent from every identifiable person depicted. AI-generated or AI-assisted content must be labelled, must not imitate a real person without documented permission, and must not be used for deception.</p></section>
    <section className="legal-section"><h2>6. Safety moderation and removal</h2><p>Uploads enter a private quarantine until automated screening and/or human review is complete. We may reject, remove, disable access to, preserve evidence for, or report content and accounts that may violate this agreement or Indian law. Automated checks can be imperfect; a moderation decision may be appealed through the reporting portal. We do not promise that every prohibited item will be detected before publication.</p><p>Report suspected child sexual abuse, non-consensual intimate imagery, impersonation, threats, privacy violations, copyright issues, or other unlawful content at <Link href="/content-removal">/content-removal</Link>. In urgent danger, contact local law enforcement first.</p></section>
    <section className="legal-section"><h2>7. AI tools and provider credits</h2><p>AI credits are usage units, not cash, deposits, or transferable property. Provider availability, model limits, safety policies, and pricing may change. We may refuse unsafe prompts, expire unused promotional units, or refund unused paid units where required by law. Never upload private or sensitive material to a third-party model without the required consent.</p></section>
    <section className="legal-section"><h2>8. Grievance, appeals, and law</h2><p>We maintain a reporting and appeal process with a reference number. We aim to acknowledge complaints promptly and communicate status where legally and operationally possible. These terms are governed by the laws of India, subject to mandatory consumer and data-protection rights. Nothing here excludes rights that cannot lawfully be excluded.</p></section>
    <section className="legal-section"><h2>9. Contact</h2><p>For support, billing, privacy, creator, or grievance requests, use the contact details published in the application settings and invoice. Keep your report factual and do not include unnecessary identity documents or intimate files.</p></section>
  </main></div>;
}
