import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title:"Privacy Policy | Nina Kurain", description:"India-first privacy notice for the Nina Kurain service." };

export default function PrivacyPolicyPage(){return <div className="legal-shell"><header className="legal-header"><div className="legal-header-inner"><div className="legal-brand"><Link href="/" className="legal-brand-link"><span className="legal-brand-dot"/><span className="legal-brand-title">NINA KURAIN</span></Link><span className="legal-badge">PRIVACY</span></div><div className="legal-nav-actions"><Link href="/" className="legal-btn legal-btn-secondary">Back to Home</Link><Link href="/terms-and-conditions" className="legal-btn legal-btn-secondary">Terms</Link><Link href="/content-removal" className="legal-btn legal-btn-secondary">Report Content</Link></div></div></header><main className="legal-main" style={{maxWidth:920,margin:"0 auto",padding:"48px 24px"}}>
  <h1 className="legal-title">Privacy Policy</h1><p className="legal-meta">Version 3.0.0 · Last updated 30 September 2026 · India</p>
  <div className="legal-callout highlight"><h2>Data minimisation by design</h2><p>We collect what is needed to operate accounts, subscriptions, creator tools, safety moderation, support, and lawful compliance. We do not sell personal data.</p></div>
  <section className="legal-section"><h2>1. Data we collect</h2><p>Depending on how you use the service, this may include name or alias, email, phone number, password hash, profile information, subscription and payment status, creator application and payout information, uploaded media, AI prompts or job metadata, reports, support messages, device/security logs, and consent records.</p></section>
  <section className="legal-section"><h2>2. Why we use it</h2><ul><li>Authenticate accounts and provide requested features.</li><li>Process payments, receipts, taxes, refunds, settlement holds, and creator earnings.</li><li>Screen and review uploads, prevent abuse, respond to reports, and protect users.</li><li>Operate AI providers only when you request a generation and have credits.</li><li>Meet legal, security, audit, and dispute-resolution obligations.</li></ul></section>
  <section className="legal-section"><h2>3. Sharing and processors</h2><p>We share only what is necessary with infrastructure, storage, email, Razorpay, Google Drive when connected by an administrator, AI providers selected for a generation request, and professional or legal advisers where required. Payment credentials are handled by the payment provider and are not stored as raw card data by this application. Provider-specific retention and transfer terms also apply.</p></section>
  <section className="legal-section"><h2>4. Media and safety data</h2><p>Uploaded media is stored in private storage and quarantined before publication. Moderation records, decisions, reports, and relevant evidence may be retained for safety, appeals, fraud prevention, and legal obligations. Do not upload identity documents or sensitive media unless the workflow specifically asks for it and you have reviewed the purpose.</p></section>
  <section className="legal-section"><h2>5. Retention and deletion</h2><p>We retain data only for as long as needed for the stated purpose, security, disputes, accounting, tax, payment reconciliation, and legal duties. Account deletion may not immediately erase records that must be preserved by law or for an active safety investigation. We will delete or anonymise data when those reasons end.</p></section>
  <section className="legal-section"><h2>6. Your choices</h2><p>You may request access, correction, deletion, consent withdrawal, or information about processing, subject to identity checks and legal exceptions. Use the support or grievance contact displayed in the service. You can also report content at <Link href="/content-removal">/content-removal</Link>.</p></section>
  <section className="legal-section"><h2>7. Security and children</h2><p>We use access controls, private media delivery, rate limits, audit logs, and safe failure defaults. No online system is completely secure. The service is not for people under 18; if we learn that a minor has an account or is depicted in prohibited content, we will restrict access and take appropriate action.</p></section>
  <section className="legal-section"><h2>8. Contact</h2><p>The operator must publish its legal name, address, privacy contact, and grievance officer details in the application before launch. Until configured, treat the service as a development deployment and do not collect production identity or payment data.</p></section>
</main></div>}
