export interface PhotoItem {
  slug: string;
  title: string;
  heading: string;
  tag: string;
  category: "Portraits" | "Editorial" | "Studio" | "Fashion";
  src: string;
  alt: string;
  width: number;
  height: number;
  caption: string;
  description: string;
  datePublished: string;
  locationCreated?: string;
  tags: string[];
  isPremium?: boolean;
}

export const PHOTOS_DATA: PhotoItem[] = [
  {
    "slug": "nina-kurain-photo-01",
    "title": "Signature Studio Portraiture — Frame 01",
    "heading": "Nina Kurain — Signature Studio Portraiture — Frame 01",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-01.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 01",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-02",
    "title": "Minimalist Light Study — Frame 02",
    "heading": "Nina Kurain — Minimalist Light Study — Frame 02",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-02.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 02",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-03",
    "title": "Contemporary Ethnic Silhouette — Frame 03",
    "heading": "Nina Kurain — Contemporary Ethnic Silhouette — Frame 03",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-03.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 03",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-04",
    "title": "Reflective Studio Framing — Frame 04",
    "heading": "Nina Kurain — Reflective Studio Framing — Frame 04",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-04.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 04",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-05",
    "title": "Visual Storytelling Essay — Frame 05",
    "heading": "Nina Kurain — Visual Storytelling Essay — Frame 05",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-05.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 05",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-06",
    "title": "Monochromatic Mood Study — Frame 06",
    "heading": "Nina Kurain — Monochromatic Mood Study — Frame 06",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-06.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 06",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-07",
    "title": "Golden Hour Studio Aura — Frame 07",
    "heading": "Nina Kurain — Golden Hour Studio Aura — Frame 07",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-07.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 07",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-08",
    "title": "High-Contrast Profile — Frame 08",
    "heading": "Nina Kurain — High-Contrast Profile — Frame 08",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-08.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 08",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-09",
    "title": "Subtle Chiaroscuro Form — Frame 09",
    "heading": "Nina Kurain — Subtle Chiaroscuro Form — Frame 09",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-09.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 09",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-10",
    "title": "Intimate Studio Focus — Frame 10",
    "heading": "Nina Kurain — Intimate Studio Focus — Frame 10",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-10.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 10",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-11",
    "title": "Editorial Grace & Texture — Frame 11",
    "heading": "Nina Kurain — Editorial Grace & Texture — Frame 11",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-11.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 11",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-12",
    "title": "Cinematic Portrait Mood — Frame 12",
    "heading": "Nina Kurain — Cinematic Portrait Mood — Frame 12",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-12.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 12",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-13",
    "title": "Sartorial Elegance Frame — Frame 13",
    "heading": "Nina Kurain — Sartorial Elegance Frame — Frame 13",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-13.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 13",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-14",
    "title": "Warm Ambient Illumination — Frame 14",
    "heading": "Nina Kurain — Warm Ambient Illumination — Frame 14",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-14.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 14",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-15",
    "title": "Fine Art Studio Study — Frame 15",
    "heading": "Nina Kurain — Fine Art Studio Study — Frame 15",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-15.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 15",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-16",
    "title": "Signature Studio Portraiture — Frame 16",
    "heading": "Nina Kurain — Signature Studio Portraiture — Frame 16",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-16.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 16",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-17",
    "title": "Minimalist Light Study — Frame 17",
    "heading": "Nina Kurain — Minimalist Light Study — Frame 17",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-17.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 17",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-18",
    "title": "Contemporary Ethnic Silhouette — Frame 18",
    "heading": "Nina Kurain — Contemporary Ethnic Silhouette — Frame 18",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-18.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 18",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-19",
    "title": "Reflective Studio Framing — Frame 19",
    "heading": "Nina Kurain — Reflective Studio Framing — Frame 19",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-19.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 19",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-21",
    "title": "Visual Storytelling Essay — Frame 21",
    "heading": "Nina Kurain — Visual Storytelling Essay — Frame 21",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-21.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 21",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-22",
    "title": "Monochromatic Mood Study — Frame 22",
    "heading": "Nina Kurain — Monochromatic Mood Study — Frame 22",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-22.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 22",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-23",
    "title": "Golden Hour Studio Aura — Frame 23",
    "heading": "Nina Kurain — Golden Hour Studio Aura — Frame 23",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-23.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 23",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-30",
    "title": "High-Contrast Profile — Frame 30",
    "heading": "Nina Kurain — High-Contrast Profile — Frame 30",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-30.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 30",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-31",
    "title": "Subtle Chiaroscuro Form — Frame 31",
    "heading": "Nina Kurain — Subtle Chiaroscuro Form — Frame 31",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-31.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 31",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-32",
    "title": "Intimate Studio Focus — Frame 32",
    "heading": "Nina Kurain — Intimate Studio Focus — Frame 32",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-32.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 32",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-33",
    "title": "Editorial Grace & Texture — Frame 33",
    "heading": "Nina Kurain — Editorial Grace & Texture — Frame 33",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-33.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 33",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-34",
    "title": "Cinematic Portrait Mood — Frame 34",
    "heading": "Nina Kurain — Cinematic Portrait Mood — Frame 34",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-34.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 34",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-35",
    "title": "Sartorial Elegance Frame — Frame 35",
    "heading": "Nina Kurain — Sartorial Elegance Frame — Frame 35",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-35.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 35",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-36",
    "title": "Warm Ambient Illumination — Frame 36",
    "heading": "Nina Kurain — Warm Ambient Illumination — Frame 36",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-36.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 36",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-37",
    "title": "Fine Art Studio Study — Frame 37",
    "heading": "Nina Kurain — Fine Art Studio Study — Frame 37",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-37.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 37",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-38",
    "title": "Signature Studio Portraiture — Frame 38",
    "heading": "Nina Kurain — Signature Studio Portraiture — Frame 38",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-38.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 38",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-39",
    "title": "Minimalist Light Study — Frame 39",
    "heading": "Nina Kurain — Minimalist Light Study — Frame 39",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-39.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 39",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-40",
    "title": "Contemporary Ethnic Silhouette — Frame 40",
    "heading": "Nina Kurain — Contemporary Ethnic Silhouette — Frame 40",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-40.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 40",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-41",
    "title": "Reflective Studio Framing — Frame 41",
    "heading": "Nina Kurain — Reflective Studio Framing — Frame 41",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-41.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 41",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-42",
    "title": "Visual Storytelling Essay — Frame 42",
    "heading": "Nina Kurain — Visual Storytelling Essay — Frame 42",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-42.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 42",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-43",
    "title": "Monochromatic Mood Study — Frame 43",
    "heading": "Nina Kurain — Monochromatic Mood Study — Frame 43",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-43.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 43",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-44",
    "title": "Golden Hour Studio Aura — Frame 44",
    "heading": "Nina Kurain — Golden Hour Studio Aura — Frame 44",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-44.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 44",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-45",
    "title": "High-Contrast Profile — Frame 45",
    "heading": "Nina Kurain — High-Contrast Profile — Frame 45",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-45.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 45",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-46",
    "title": "Subtle Chiaroscuro Form — Frame 46",
    "heading": "Nina Kurain — Subtle Chiaroscuro Form — Frame 46",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-46.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 46",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-47",
    "title": "Intimate Studio Focus — Frame 47",
    "heading": "Nina Kurain — Intimate Studio Focus — Frame 47",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-47.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 47",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-48",
    "title": "Editorial Grace & Texture — Frame 48",
    "heading": "Nina Kurain — Editorial Grace & Texture — Frame 48",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-48.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 48",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-49",
    "title": "Cinematic Portrait Mood — Frame 49",
    "heading": "Nina Kurain — Cinematic Portrait Mood — Frame 49",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-49.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 49",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-50",
    "title": "Sartorial Elegance Frame — Frame 50",
    "heading": "Nina Kurain — Sartorial Elegance Frame — Frame 50",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-50.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 50",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-51",
    "title": "Warm Ambient Illumination — Frame 51",
    "heading": "Nina Kurain — Warm Ambient Illumination — Frame 51",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-51.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 51",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-52",
    "title": "Fine Art Studio Study — Frame 52",
    "heading": "Nina Kurain — Fine Art Studio Study — Frame 52",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-52.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 52",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-53",
    "title": "Signature Studio Portraiture — Frame 53",
    "heading": "Nina Kurain — Signature Studio Portraiture — Frame 53",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-53.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 53",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-54",
    "title": "Minimalist Light Study — Frame 54",
    "heading": "Nina Kurain — Minimalist Light Study — Frame 54",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-54.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 54",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-55",
    "title": "Contemporary Ethnic Silhouette — Frame 55",
    "heading": "Nina Kurain — Contemporary Ethnic Silhouette — Frame 55",
    "tag": "Studio Series",
    "category": "Studio",
    "src": "/nina-gallery/nina-kurain-55.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 55",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic studio photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this studio piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Studio",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-56",
    "title": "Reflective Studio Framing — Frame 56",
    "heading": "Nina Kurain — Reflective Studio Framing — Frame 56",
    "tag": "Portraits Series",
    "category": "Portraits",
    "src": "/nina-gallery/nina-kurain-56.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 56",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic portraits photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this portraits piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Portraits",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-57",
    "title": "Visual Storytelling Essay — Frame 57",
    "heading": "Nina Kurain — Visual Storytelling Essay — Frame 57",
    "tag": "Editorial Series",
    "category": "Editorial",
    "src": "/nina-gallery/nina-kurain-57.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 57",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic editorial photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this editorial piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Editorial",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  },
  {
    "slug": "nina-kurain-photo-58",
    "title": "Monochromatic Mood Study — Frame 58",
    "heading": "Nina Kurain — Monochromatic Mood Study — Frame 58",
    "tag": "Fashion Series",
    "category": "Fashion",
    "src": "/nina-gallery/nina-kurain-58.jpeg",
    "alt": "Nina Kurain — Digital Creator authentic studio photograph 58",
    "width": 1200,
    "height": 1600,
    "caption": "Authentic fashion photograph of Nina Kurain, capturing contemporary visual direction and natural aesthetic expression.",
    "description": "From the official Nina Kurain photography collection, this fashion piece captures authentic lighting, timeless composition, and creative digital styling.",
    "datePublished": "2026-09-24",
    "locationCreated": "Studio Archive, India",
    "tags": [
      "Nina Kurain",
      "Digital Creator",
      "Fashion",
      "Photography",
      "Official Gallery"
    ],
    "isPremium": false
  }
];
